In [1]:
import pandas as pd

In [6]:
data = {
    "student": ["Achi", "Ochi", "Muchi"],
    "homework_score": [55, 68, 83],
    "mock_exam_score": [72, 78, 94],
    "participation_score": [82, 56, 92],
    "actual_final_score": [70, 74, 93],
    "predicted_final_score": [68, 76, 90]
}
df = pd.DataFrame(data)
df

,student,homework_score,mock_exam_score,participation_score,actual_final_score,predicted_final_score
0,Achi,55,72,82,70,68
1,Ochi,68,78,56,74,76
2,Muchi,83,94,92,93,90

In [9]:
df["error"] = df["actual_final_score"] -  df["predicted_final_score"]
df

,student,homework_score,mock_exam_score,participation_score,actual_final_score,predicted_final_score,error
0,Achi,55,72,82,70,68,2
1,Ochi,68,78,56,74,76,-2
2,Muchi,83,94,92,93,90,3

In [11]:
df["absolute_error"] = df["error"].abs()
df

,student,homework_score,mock_exam_score,participation_score,actual_final_score,predicted_final_score,error,absolute_error
0,Achi,55,72,82,70,68,2,2
1,Ochi,68,78,56,74,76,-2,2
2,Muchi,83,94,92,93,90,3,3

In [16]:
average_absolute_error = df["absolute_error"].mean()
print(f"The average absolute error is: {average_absolute_error:.2f}")

The average absolute error is: 2.33

In [19]:
largest_error = df[df["absolute_error"]== df["absolute_error"].max()]
largest_error

,student,homework_score,mock_exam_score,participation_score,actual_final_score,predicted_final_score,error,absolute_error
2,Muchi,83,94,92,93,90,3,3