In [1]:
import pandas as pd

# Exercise 1 --------- Study Hours --> Score

In [2]:
data = {
    "study_hours": [1, 2, 3, 4, 5, 6],
    "score": [40, 48, 55, 63, 70, 78]
}
df=pd.DataFrame(data)
df

   study_hours  score
0            1     40
1            2     48
2            3     55
3            4     63
4            5     70
5            6     78

In [3]:
X = df[["study_hours"]]
y= df[["score"]]

In [4]:
print(X.shape)
print(y.shape)

(6, 1)
(6, 1)

In [5]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(X,y)

LinearRegression()

In [6]:
new_student = pd.DataFrame({
    "study_hours": [7]
})
prediction = model.predict(new_student)
prediction

array([[85.4]])

# Exercise 2 ---- Hours Worked -> Income

In [7]:
data = {
    "hours_worked": [2, 3, 4, 5, 6],
    "income": [12000, 18000, 24000, 30000, 36000]
}
df=pd.DataFrame(data)
df

   hours_worked  income
0             2   12000
1             3   18000
2             4   24000
3             5   30000
4             6   36000

In [8]:
X=df[["hours_worked"]]
y=df[["income"]]

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [12]:
new_income = pd.DataFrame({
    "hours_worked": [7]
})
prediction = model.predict(new_income)
prediction

array([[42000.]])

# Exercise 3 Advertising Spend -> Sales

In [13]:
data = {
    "advertising_spend": [10, 20, 30, 40, 50],
    "sales": [100, 160, 220, 280, 340]
}
df=pd.DataFrame(data)
df

   advertising_spend  sales
0                 10    100
1                 20    160
2                 30    220
3                 40    280
4                 50    340

In [14]:
X=df[["advertising_spend"]]
y=df[["sales"]]

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [16]:
new_sales=pd.DataFrame({
    "advertising_spend":[60]
})

prediction=model.predict(new_sales)
prediction

array([[400.]])

# Exercise 4 --- Practice Hours -> Test Score

In [19]:
data ={
    "practice_hours": [1, 2, 4, 5, 7],
    "test_score": [45, 52, 65, 72, 85]
}
df=pd.DataFrame(data)
df

   practice_hours  test_score
0               1          45
1               2          52
2               4          65
3               5          72
4               7          85

In [20]:
X=df[["practice_hours"]]
y=df[["test_score"]]

In [23]:
from sklearn.linear_model import LinearRegression
model =LinearRegression()
model.fit(X,y)

LinearRegression()

In [24]:
new_score = pd.DataFrame({
    "practice_hours":[6]
})
prediction = model.predict(new_score)
prediction

array([[78.44736842]])

# Exercise 5  -- House Size --> House Price

In [25]:
data = {
    "house_size": [50, 75, 100, 125, 150],
    "price": [50000, 70000, 90000, 110000, 130000]
}
df= pd.DataFrame(data)
df

   house_size   price
0          50   50000
1          75   70000
2         100   90000
3         125  110000
4         150  130000

In [26]:
X=df[["house_size"]]
y=df[["price"]]

In [27]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [30]:
new_price = pd.DataFrame({
    "house_size":[175]
})
prediction = model.predict(new_price)
prediction

array([[150000.]])