In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("student_final_score_project.csv")
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.3,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,NaN,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.3,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.1,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.1,43.4,4,5.8,78.1

In [4]:
df.head(5)

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.7,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.5,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.9,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.1,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.6,55.4,4,6.9,83.9

In [5]:
df.shape

(500, 8)

In [6]:
df.isnull()

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False
496,False,False,False,True,False,False,False,False
497,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False

In [24]:
df["study_hours"] = df["study_hours"].fillna(df["study_hours"].mean())
df["attendance"] = df["attendance"].fillna(df["attendance"].mean())
df["homework_score"] = df["homework_score"].fillna(df["homework_score"].mean())
df["previous_test_score"] = df["previous_test_score"].fillna(df["previous_test_score"].mean())
df["tutoring_sessions"] =df["tutoring_sessions"].fillna(df["tutoring_sessions"].mean())
df["sleep_hours"] = df["sleep_hours"].fillna(df["sleep_hours"].mean())
df["final_score"] = df["final_score"].fillna(df["final_score"].mean())
df

,student_id,study_hours,attendance,homework_score,previous_test_score,tutoring_sessions,sleep_hours,final_score
0,STU0001,1.4,77.6,70.700000,86.6,0,8.5,79.4
1,STU0002,3.7,80.8,90.500000,81.6,3,7.9,84.2
2,STU0003,4.9,65.8,76.900000,41.6,0,6.5,72.5
3,STU0004,5.6,64.5,55.100000,93.8,2,8.1,79.3
4,STU0005,8.0,78.1,44.600000,55.4,4,6.9,83.9
...,...,...,...,...,...,...,...,...
495,STU0496,7.7,55.3,98.300000,77.2,5,8.8,100.0
496,STU0497,1.6,67.3,69.903975,40.5,2,5.8,56.1
497,STU0498,6.7,63.5,82.300000,90.8,1,7.3,88.3
498,STU0499,6.0,78.2,94.100000,48.2,3,5.9,89.5
499,STU0500,6.8,62.9,70.100000,43.4,4,5.8,78.1

In [25]:
df.isnull().sum()

student_id             0
study_hours            0
attendance             0
homework_score         0
previous_test_score    0
tutoring_sessions      0
sleep_hours            0
final_score            0
dtype: int64

In [26]:
X = df[[
        "study_hours",
        "attendance",
        "homework_score",
        "previous_test_score",
        "tutoring_sessions",
        "sleep_hours"
    ]]
y = df["final_score"]

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.4,
    random_state = 42
)

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()

In [31]:
model.fit(X_train, y_train)

LinearRegression()

In [36]:
predictions = model.predict(X_test)
predictions

array([ 76.82669709,  74.32257532,  61.23084119,  80.90349657,
        66.60625156,  75.74682784,  58.97385482,  89.8816457 ,
        73.7236375 ,  91.13667321,  72.52507641,  88.14275457,
        75.19939575,  76.57413303,  82.3022936 ,  70.27210842,
       101.36371666,  74.0267129 ,  96.99812899,  74.57068554,
        83.27222815,  92.51855209,  86.54270432,  77.50518061,
        73.17536353,  69.70740379,  92.91305212,  84.10469763,
        80.18732699,  83.04385944,  73.11508683,  77.80064742,
        81.33519949,  60.78341704,  70.51463603,  85.81495908,
        61.29685687,  76.50529294,  82.96681664,  69.7115938 ,
        75.6507933 ,  64.96365663,  69.78547193,  88.21006039,
        76.07612341,  82.56717881,  74.12121657,  88.69427772,
        71.58156523,  78.55155128,  74.92294903,  87.95714516,
        75.71414478,  68.59281043,  63.77546172,  79.61654236,
        62.71996023,  88.81916765,  56.14159969,  64.89676104,
        71.50990732,  67.61670022,  78.01860599,  86.45082788,
        73.42641244,  83.50374686,  74.81315524,  70.05552066,
        97.60647107,  76.04430429,  67.17259364,  91.27428558,
        98.70466098,  73.51875215,  91.25410936,  61.76086105,
        81.9961633 ,  78.71488359,  76.73532012,  72.28450054,
        84.51473007,  79.48589568,  82.04194171,  80.36470769,
        81.98249999,  66.75335248,  81.05905123,  88.57052513,
        72.79581194,  86.36423071,  66.7382848 ,  78.52872682,
        77.74630545,  79.62623855,  78.0384171 ,  72.01667241,
        69.61488815,  67.77847158,  69.49488483,  73.41317547,
        59.68881536,  81.71126628,  93.1276416 ,  64.93016421,
        80.9831198 ,  81.48884482,  76.66226059,  67.29797801,
        76.23757767,  70.95952879,  75.96490113,  59.99537702,
        91.74043256,  74.65719856,  98.08463731,  76.80452622,
        83.64997352,  95.34800623,  75.1834839 ,  73.97122677,
        83.20784602,  81.73147134,  77.57287088,  79.42606497,
        71.67573998,  75.28213417,  76.61748453,  88.03028024,
        81.66318269,  79.73573632,  83.15700227,  58.91354879,
        61.16754342,  80.84496369,  94.28272224,  82.33321992,
        83.39258175,  82.90742648,  78.15154196,  89.08081463,
        79.04293984,  84.98291592,  80.56083647,  75.4941491 ,
        92.73563152,  64.28334704,  71.28395176,  69.76501603,
        86.66619886,  70.83400654,  85.48694337,  83.76015635,
        65.24775121,  64.98660166,  56.2974604 ,  82.20599989,
        86.68231623,  87.71409369,  67.09269337,  68.73863833,
        72.7632582 ,  83.48351619,  88.72877126,  77.92669814,
        81.28652484,  62.13821371,  63.67502123,  97.14167082,
        81.13610785,  73.25795372,  81.37596034,  78.18670528,
        87.41541932,  59.37633239,  67.7361626 ,  71.13142354,
        81.29776347,  84.2243638 ,  86.78878914,  84.78668758,
        72.68432882,  87.75983261,  91.4709734 ,  66.46594951,
        64.64370984,  78.06240414,  79.72128003,  84.65791885,
        77.68320113,  78.25615362,  86.938541  ,  68.54949876,
        72.87878625,  73.00347011,  84.73981036,  65.1640616 ,
        83.65588418,  78.57549277,  82.37872604,  77.51217343])

In [37]:
results = pd.DataFrame({
    "Actual_score": y_test.values,
    "Predicted_score": predictions
})
results

     Actual_score  Predicted_score
0            83.4        76.826697
1            74.0        74.322575
2            62.2        61.230841
3            82.1        80.903497
4            60.2        66.606252
..            ...              ...
195          58.1        65.164062
196          85.4        83.655884
197          76.2        78.575493
198          77.2        82.378726
199          81.3        77.512173

[200 rows x 2 columns]

In [38]:
from sklearn.metrics import mean_absolute_error, r2_score

In [39]:
mae = mean_absolute_error(y_test, predictions)
print(mae)

4.27329662805314

In [40]:
r2= r2_score(y_test, predictions)
print(r2)

0.7352442745748654