In [1]:
import pandas as pd

In [4]:
data = {
    "student": ["Student A", "Student B", "Student C", "Student D", "Student E"],
    "weekly_practice_hours": [1, 2, 4, 5, 7],
    "attendance": [60, 75, 85, 95, 90],
    "actual_test_score": [45, 58, 74, 88, 86],
    "predicted_score": [50, 60, 72, 84, 90]
}
df = pd.DataFrame(data)
df

,student,weekly_practice_hours,attendance,actual_test_score,predicted_score
0,Student A,1,60,45,50
1,Student B,2,75,58,60
2,Student C,4,85,74,72
3,Student D,5,95,88,84
4,Student E,7,90,86,90

In [6]:
df["error"] = df["actual_test_score"] - df["predicted_score"]
df

,student,weekly_practice_hours,attendance,actual_test_score,predicted_score,error
0,Student A,1,60,45,50,-5
1,Student B,2,75,58,60,-2
2,Student C,4,85,74,72,2
3,Student D,5,95,88,84,4
4,Student E,7,90,86,90,-4

In [7]:
df["absolute_error"] = df["error"].abs()
df

,student,weekly_practice_hours,attendance,actual_test_score,predicted_score,error,absolute_error
0,Student A,1,60,45,50,-5,5
1,Student B,2,75,58,60,-2,2
2,Student C,4,85,74,72,2,2
3,Student D,5,95,88,84,4,4
4,Student E,7,90,86,90,-4,4